[package]
name = "comic_uldb_server"
version = "0.0.0"
authors = ["Sunip Mukherjee <sunipkmukherjee@gmail.com>"]
edition = "2021"

[dependencies]
image = { version = "0.25", default-features = false, features = [
    "rayon",
    "png",
] }
refimage = { version = ">= 1.0.0-pre", features = ["rayon", "image", "fitsio"] }
chrono = { version = "0.4", default-features = false, features = [
    "std",
    "clock",
    "serde",
] }
tungstenite = { version = "0.23" }
packet = { workspace = true }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.40", features = ["full"] }
futures-util = "0.3"
log = "0.4"
env_logger = "0.11"
tokio-tungstenite = "*"
futures-channel = "0.3"
generic-camera = { workspace = true, features = ["server", "dummy"] }
bincode = { workspace = true }
generic-camera-asi = "0.0.11"
configparser = { version = "3.1", features = ["tokio"] }
datastor = { git = "https://github.com/sunipkm/datastor" }
linux-embedded-hal = { version = "0.4", features = ["async-tokio"] }
mcp9808 = { workspace = true, features = ["std"] }
embedded-hal = "1.0.0"
nix = { version = "0.29", features = ["time"] }
ublox-gps-tec = { workspace = true }
bno055 = { workspace = true, features = ["serde", "std"] }
serialport = "4.7.1"
tokio-serial = { version = "5.4.5", features = ["bytes", "codec", "libudev", "tokio-util"] }

[features]
default = ["uhubctl_toradex"]
uhubctl_pi = []
uhubctl_toradex = []
full = ["uhubctl_toradex"]
